[2025-07-09T10:37:18.651+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecommerce_etl_pipeline.extract_transform_sales scheduled__2025-07-09T10:36:15.291024+00:00 [queued]>
[2025-07-09T10:37:18.655+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecommerce_etl_pipeline.extract_transform_sales scheduled__2025-07-09T10:36:15.291024+00:00 [queued]>
[2025-07-09T10:37:18.655+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2025-07-09T10:37:18.661+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract_transform_sales> on 2025-07-09 10:36:15.291024+00:00
[2025-07-09T10:37:18.664+0000] {standard_task_runner.py:57} INFO - Started process 3552 to run task
[2025-07-09T10:37:18.666+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ecommerce_etl_pipeline', 'extract_transform_sales', 'scheduled__2025-07-09T10:36:15.291024+00:00', '--job-id', '515', '--raw', '--subdir', 'DAGS_FOLDER/ecommerce_etl_dag.py', '--cfg-path', '/tmp/tmppmyxqx0f']
[2025-07-09T10:37:18.667+0000] {standard_task_runner.py:85} INFO - Job 515: Subtask extract_transform_sales
[2025-07-09T10:37:18.791+0000] {task_command.py:415} INFO - Running <TaskInstance: ecommerce_etl_pipeline.extract_transform_sales scheduled__2025-07-09T10:36:15.291024+00:00 [running]> on host fc060bb3c09b
[2025-07-09T10:37:18.840+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_team' AIRFLOW_CTX_DAG_ID='ecommerce_etl_pipeline' AIRFLOW_CTX_TASK_ID='extract_transform_sales' AIRFLOW_CTX_EXECUTION_DATE='2025-07-09T10:36:15.291024+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-09T10:36:15.291024+00:00'
[2025-07-09T10:37:18.841+0000] {ecommerce_etl_dag.py:151} INFO - Bắt đầu extract sales data...
[2025-07-09T10:37:18.846+0000] {base.py:73} INFO - Using connection ID 'postgres_data' for task execution.
[2025-07-09T10:37:18.849+0000] {sql.py:418} INFO - Running statement: TRUNCATE TABLE target_data.fact_sales CASCADE;, parameters: None
[2025-07-09T10:37:18.857+0000] {base.py:73} INFO - Using connection ID 'postgres_data' for task execution.
[2025-07-09T10:37:18.863+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.9/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-07-09T10:37:18.870+0000] {ecommerce_etl_dag.py:178} INFO - Extracted 978 sales records
[2025-07-09T10:37:18.874+0000] {base.py:73} INFO - Using connection ID 'postgres_data' for task execution.
[2025-07-09T10:37:18.897+0000] {ecommerce_etl_dag.py:197} INFO - Loaded 978 sales records vào fact_sales
[2025-07-09T10:37:18.898+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-07-09T10:37:18.903+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ecommerce_etl_pipeline, task_id=extract_transform_sales, execution_date=20250709T103615, start_date=20250709T103718, end_date=20250709T103718
[2025-07-09T10:37:18.929+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-07-09T10:37:18.946+0000] {taskinstance.py:2784} INFO - 1 downstream tasks scheduled from follow-on schedule check
