[2025-07-09T10:08:17.663+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecommerce_etl_pipeline.extract_transform_sales scheduled__2025-07-09T10:07:14.875527+00:00 [queued]>
[2025-07-09T10:08:17.667+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecommerce_etl_pipeline.extract_transform_sales scheduled__2025-07-09T10:07:14.875527+00:00 [queued]>
[2025-07-09T10:08:17.667+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2025-07-09T10:08:17.672+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract_transform_sales> on 2025-07-09 10:07:14.875527+00:00
[2025-07-09T10:08:17.676+0000] {standard_task_runner.py:57} INFO - Started process 2372 to run task
[2025-07-09T10:08:17.678+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ecommerce_etl_pipeline', 'extract_transform_sales', 'scheduled__2025-07-09T10:07:14.875527+00:00', '--job-id', '370', '--raw', '--subdir', 'DAGS_FOLDER/ecommerce_etl_dag.py', '--cfg-path', '/tmp/tmprazjk3w4']
[2025-07-09T10:08:17.679+0000] {standard_task_runner.py:85} INFO - Job 370: Subtask extract_transform_sales
[2025-07-09T10:08:17.703+0000] {task_command.py:415} INFO - Running <TaskInstance: ecommerce_etl_pipeline.extract_transform_sales scheduled__2025-07-09T10:07:14.875527+00:00 [running]> on host fc060bb3c09b
[2025-07-09T10:08:17.838+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_team' AIRFLOW_CTX_DAG_ID='ecommerce_etl_pipeline' AIRFLOW_CTX_TASK_ID='extract_transform_sales' AIRFLOW_CTX_EXECUTION_DATE='2025-07-09T10:07:14.875527+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-09T10:07:14.875527+00:00'
[2025-07-09T10:08:17.839+0000] {ecommerce_etl_dag.py:151} INFO - Bắt đầu extract sales data...
[2025-07-09T10:08:17.843+0000] {base.py:73} INFO - Using connection ID 'postgres_data' for task execution.
[2025-07-09T10:08:17.845+0000] {sql.py:418} INFO - Running statement: TRUNCATE TABLE target_data.fact_sales CASCADE;, parameters: None
[2025-07-09T10:08:17.857+0000] {base.py:73} INFO - Using connection ID 'postgres_data' for task execution.
[2025-07-09T10:08:17.862+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.9/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-07-09T10:08:17.866+0000] {ecommerce_etl_dag.py:178} INFO - Extracted 359 sales records
[2025-07-09T10:08:17.869+0000] {base.py:73} INFO - Using connection ID 'postgres_data' for task execution.
[2025-07-09T10:08:17.879+0000] {ecommerce_etl_dag.py:197} INFO - Loaded 359 sales records vào fact_sales
[2025-07-09T10:08:17.880+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-07-09T10:08:17.884+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ecommerce_etl_pipeline, task_id=extract_transform_sales, execution_date=20250709T100714, start_date=20250709T100817, end_date=20250709T100817
[2025-07-09T10:08:17.905+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-07-09T10:08:17.919+0000] {taskinstance.py:2784} INFO - 1 downstream tasks scheduled from follow-on schedule check
