[2025-07-09T09:52:16.943+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecommerce_etl_pipeline.extract_transform_sales scheduled__2025-07-09T09:51:14.875527+00:00 [queued]>
[2025-07-09T09:52:16.947+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecommerce_etl_pipeline.extract_transform_sales scheduled__2025-07-09T09:51:14.875527+00:00 [queued]>
[2025-07-09T09:52:16.947+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2025-07-09T09:52:16.953+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract_transform_sales> on 2025-07-09 09:51:14.875527+00:00
[2025-07-09T09:52:16.955+0000] {standard_task_runner.py:57} INFO - Started process 1731 to run task
[2025-07-09T09:52:16.958+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ecommerce_etl_pipeline', 'extract_transform_sales', 'scheduled__2025-07-09T09:51:14.875527+00:00', '--job-id', '290', '--raw', '--subdir', 'DAGS_FOLDER/ecommerce_etl_dag.py', '--cfg-path', '/tmp/tmp1kf_w5sn']
[2025-07-09T09:52:16.960+0000] {standard_task_runner.py:85} INFO - Job 290: Subtask extract_transform_sales
[2025-07-09T09:52:16.984+0000] {task_command.py:415} INFO - Running <TaskInstance: ecommerce_etl_pipeline.extract_transform_sales scheduled__2025-07-09T09:51:14.875527+00:00 [running]> on host fc060bb3c09b
[2025-07-09T09:52:17.119+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_team' AIRFLOW_CTX_DAG_ID='ecommerce_etl_pipeline' AIRFLOW_CTX_TASK_ID='extract_transform_sales' AIRFLOW_CTX_EXECUTION_DATE='2025-07-09T09:51:14.875527+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-09T09:51:14.875527+00:00'
[2025-07-09T09:52:17.119+0000] {ecommerce_etl_dag.py:151} INFO - Bắt đầu extract sales data...
[2025-07-09T09:52:17.123+0000] {base.py:73} INFO - Using connection ID 'postgres_data' for task execution.
[2025-07-09T09:52:17.125+0000] {sql.py:418} INFO - Running statement: TRUNCATE TABLE target_data.fact_sales CASCADE;, parameters: None
[2025-07-09T09:52:17.134+0000] {base.py:73} INFO - Using connection ID 'postgres_data' for task execution.
[2025-07-09T09:52:17.139+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.9/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-07-09T09:52:17.143+0000] {ecommerce_etl_dag.py:178} INFO - Extracted 359 sales records
[2025-07-09T09:52:17.147+0000] {base.py:73} INFO - Using connection ID 'postgres_data' for task execution.
[2025-07-09T09:52:17.157+0000] {ecommerce_etl_dag.py:197} INFO - Loaded 359 sales records vào fact_sales
[2025-07-09T09:52:17.158+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-07-09T09:52:17.163+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ecommerce_etl_pipeline, task_id=extract_transform_sales, execution_date=20250709T095114, start_date=20250709T095216, end_date=20250709T095217
[2025-07-09T09:52:17.180+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-07-09T09:52:17.193+0000] {taskinstance.py:2784} INFO - 1 downstream tasks scheduled from follow-on schedule check
