[2025-07-09T10:47:16.637+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecommerce_etl_pipeline.extract_transform_customers scheduled__2025-07-09T10:46:15.291024+00:00 [queued]>
[2025-07-09T10:47:16.644+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecommerce_etl_pipeline.extract_transform_customers scheduled__2025-07-09T10:46:15.291024+00:00 [queued]>
[2025-07-09T10:47:16.645+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2025-07-09T10:47:16.655+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract_transform_customers> on 2025-07-09 10:46:15.291024+00:00
[2025-07-09T10:47:16.658+0000] {standard_task_runner.py:57} INFO - Started process 3958 to run task
[2025-07-09T10:47:16.660+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ecommerce_etl_pipeline', 'extract_transform_customers', 'scheduled__2025-07-09T10:46:15.291024+00:00', '--job-id', '563', '--raw', '--subdir', 'DAGS_FOLDER/ecommerce_etl_dag.py', '--cfg-path', '/tmp/tmprszvjz03']
[2025-07-09T10:47:16.662+0000] {standard_task_runner.py:85} INFO - Job 563: Subtask extract_transform_customers
[2025-07-09T10:47:16.842+0000] {task_command.py:415} INFO - Running <TaskInstance: ecommerce_etl_pipeline.extract_transform_customers scheduled__2025-07-09T10:46:15.291024+00:00 [running]> on host fc060bb3c09b
[2025-07-09T10:47:16.886+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_team' AIRFLOW_CTX_DAG_ID='ecommerce_etl_pipeline' AIRFLOW_CTX_TASK_ID='extract_transform_customers' AIRFLOW_CTX_EXECUTION_DATE='2025-07-09T10:46:15.291024+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-09T10:46:15.291024+00:00'
[2025-07-09T10:47:16.887+0000] {ecommerce_etl_dag.py:32} INFO - Bắt đầu extract customers data...
[2025-07-09T10:47:16.891+0000] {base.py:73} INFO - Using connection ID 'postgres_data' for task execution.
[2025-07-09T10:47:16.897+0000] {sql.py:418} INFO - Running statement: TRUNCATE TABLE target_data.dim_customers CASCADE;, parameters: None
[2025-07-09T10:47:16.923+0000] {base.py:73} INFO - Using connection ID 'postgres_data' for task execution.
[2025-07-09T10:47:16.933+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.9/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-07-09T10:47:16.938+0000] {ecommerce_etl_dag.py:59} INFO - Extracted 455 customers
[2025-07-09T10:47:16.943+0000] {base.py:73} INFO - Using connection ID 'postgres_data' for task execution.
[2025-07-09T10:47:16.955+0000] {ecommerce_etl_dag.py:83} INFO - Loaded 455 customers vào dim_customers
[2025-07-09T10:47:16.955+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-07-09T10:47:16.959+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ecommerce_etl_pipeline, task_id=extract_transform_customers, execution_date=20250709T104615, start_date=20250709T104716, end_date=20250709T104716
[2025-07-09T10:47:17.005+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-07-09T10:47:17.099+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
