[2025-07-09T09:17:48.432+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: ecommerce_etl_pipeline.extract_transform_customers scheduled__2025-07-09T09:16:47.397058+00:00 [queued]>
[2025-07-09T09:17:48.445+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: ecommerce_etl_pipeline.extract_transform_customers scheduled__2025-07-09T09:16:47.397058+00:00 [queued]>
[2025-07-09T09:17:48.445+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 4
[2025-07-09T09:17:48.461+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): extract_transform_customers> on 2025-07-09 09:16:47.397058+00:00
[2025-07-09T09:17:48.482+0000] {standard_task_runner.py:57} INFO - Started process 280 to run task
[2025-07-09T09:17:48.488+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'ecommerce_etl_pipeline', 'extract_transform_customers', 'scheduled__2025-07-09T09:16:47.397058+00:00', '--job-id', '102', '--raw', '--subdir', 'DAGS_FOLDER/ecommerce_etl_dag.py', '--cfg-path', '/tmp/tmp46du56c2']
[2025-07-09T09:17:48.492+0000] {standard_task_runner.py:85} INFO - Job 102: Subtask extract_transform_customers
[2025-07-09T09:17:48.566+0000] {task_command.py:415} INFO - Running <TaskInstance: ecommerce_etl_pipeline.extract_transform_customers scheduled__2025-07-09T09:16:47.397058+00:00 [running]> on host fc060bb3c09b
[2025-07-09T09:17:48.692+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data_team' AIRFLOW_CTX_DAG_ID='ecommerce_etl_pipeline' AIRFLOW_CTX_TASK_ID='extract_transform_customers' AIRFLOW_CTX_EXECUTION_DATE='2025-07-09T09:16:47.397058+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-07-09T09:16:47.397058+00:00'
[2025-07-09T09:17:48.695+0000] {ecommerce_etl_dag.py:32} INFO - Bắt đầu extract customers data...
[2025-07-09T09:17:48.879+0000] {base.py:73} INFO - Using connection ID 'postgres_data' for task execution.
[2025-07-09T09:17:48.882+0000] {sql.py:418} INFO - Running statement: TRUNCATE TABLE target_data.dim_customers CASCADE;, parameters: None
[2025-07-09T09:17:48.903+0000] {base.py:73} INFO - Using connection ID 'postgres_data' for task execution.
[2025-07-09T09:17:48.909+0000] {logging_mixin.py:151} WARNING - /home/***/.local/lib/python3.9/site-packages/***/providers/common/sql/hooks/sql.py:219 UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
[2025-07-09T09:17:48.911+0000] {ecommerce_etl_dag.py:59} INFO - Extracted 5 customers
[2025-07-09T09:17:48.918+0000] {base.py:73} INFO - Using connection ID 'postgres_data' for task execution.
[2025-07-09T09:17:48.923+0000] {ecommerce_etl_dag.py:83} INFO - Loaded 5 customers vào dim_customers
[2025-07-09T09:17:48.923+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-07-09T09:17:48.931+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=ecommerce_etl_pipeline, task_id=extract_transform_customers, execution_date=20250709T091647, start_date=20250709T091748, end_date=20250709T091748
[2025-07-09T09:17:48.973+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-07-09T09:17:48.986+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
